### ISSUE TITLE
the error of ValueError: invalid literal for int() with base 10: 'o'

### ISSUE THREAD

**Issue by shuxingcheng** [nasa-jpl/T-ENTacle#45]
Here is what I running the test for the latest version,

```
(jpl) C:\Users\ugwz\T-ENTacle\text-analysis>python knowledge_facilitator.py --i --a --e entity_name.txt C:\Users\ugwz\Desktop\JPL\NOJV\new-use-case\Abraxas\test1.pdf
Processing document  test1.pdf
Generating patterns...
Patterns generated and filtered. Number of patterns:  51739

Processing the entity: ISIP (psi)
This entity hasn't been learned yet.
Looking for patterns that are similar to the entity name.
Found similar patterns

I found the following patterns that may represent ISIP (psi).

0. rate 81.6 bpm . isip 5499 #     [3]
1. min . isip 5150 # 10     [2]
2. hard shut down . isip 5775     [1]
3. bpm . isip 4900 # . rbih     [1]
4. isip 4900 # .     [1]
5. isip 4925 # shut in wing     [1]
6. isip 4900 # . rbih     [1]
7. isip 5775 #     [9]
8. sip 5000 # . si well     [1]
9. bpm . isip 5499 #     [3]
10. shut down . isip 5775 #     [1]
11. rate 81.6 bpm . isip     [3]
12. max rate 81.6 bpm . isip 5499     [3]
13. isip 5775 # 5     [3]
14. 5 min . isip 5150     [3]
15. isip 5775     [10]
16. 5775 # 5 min . isip     [3]
17. shut down . isip 5775 # 5     [1]
18. bpm . isip 4900 # .     [1]
19. isip 4925 # shut in wing valve     [1]
20. isip 4900 # . rbih w /     [1]
21. isip 4900 # . rbih w     [1]
22. min . isip 5150 #     [3]
23. 5775 # 5 min . isip 5150     [3]
24. isip 4925 # shut in     [1]
25. isip 4925 # shut     [1]
26. 81.6 bpm . isip 5499     [3]
27. isip 5775 # 5 min .     [3]
28. min . isip 4925 # shut     [1]
29. sip 5000 # shut in well toe     [1]
30. 5 min . isip 5150 #     [3]
31. 81.6 bpm . isip 5499 #     [3]
32. min . isip 5150 # 10 min     [2]
33. min . isip 5150     [3]
34. rate 81.6 bpm . isip 5499     [3]
35. isip 5775 # 5 min . isip     [3]
36. min . isip 4925 # shut in     [1]
37. bpm . isip 5499     [3]
38. 81.6 bpm . isip     [3]
39. sip 5000     [2]
40. 5 min . isip     [3]
41. isip 5775 # 5 min     [3]
42. 15 bpm . isip 4900 # .     [1]
43. sip 5000 #     [2]
44. hard shut down . isip 5775 #     [1]
45. 15 min . isip 4925 # shut     [1]
46. max rate 81.6 bpm . isip     [3]
47. shut down . isip 5775     [1]
48. 5 min . isip 5150 # 10     [2]
49. sip 5000 # .     [1]

Please enter the indices, separated by spaces, of all of the patterns you wish to select.
Or enter s to skip this entity or v to search by value.

Processing the entity: Total vol slick water gal
This entity hasn't been learned yet.
Looking for patterns that are similar to the entity name.
Found similar patterns

I found the following patterns that may represent Total vol slick water gal.

0. sd w / 4     [1]
1. h 2 s at shakers .     [1]
2. s 3 % kcl switched and pumped     [1]
3. switched and pumped 1000 gal ' s     [1]
4. ppm h 2 s . ran 15     [1]
5. s water @ 26     [1]
6. 90 ’ w     [1]
7. x 13-3 / 8 " sow     [1]
8. 13-3 / 8 " sow     [1]
9. bbl ' s water @ 26     [1]
10. pumped 1000 gal ' s of 15     [1]
11. circulated out h 2 s     [1]
12. m x 13-3 / 8 " sow     [1]
13. 2 / s : 5 ppm     [25]
14. back additional 350 bbl ' s     [1]
15. s water @ 26 bph     [1]
16. produced 469.64 bbl ' s water     [1]
17. w / 65     [6]
18. s water @ 26 bph and 624     [1]
19. 469.64 bbl ' s water @     [1]
20. h 2 / s : 5     [25]
21. hand and h 2 s     [1]
22. additional 350 bbl ' s after     [1]
23. 350 bbl ' s after reaching     [1]
24. s . ran 15 joints 7 "     [1]
25. 900 ppm h 2 s . ran     [1]
26. h 2 s . ran     [1]
27. 2 s . ran 15 joints 7     [1]
28. gal ' s of 15 % hcl     [1]
29. s water @ 26 bph and     [1]
30. units with 900 ppm h 2 s     [1]
31. 469.64 bbl ' s water @ 26     [1]
32. bbl ' s water @ 26 bph     [1]
33. ppm h 2 s . rotate     [1]
34. 2 s . ran     [1]
35. produced 469.64 bbl ' s water @     [1]
36. 2 / s : 35 ppm c     [1]
37. produced 469.64 bbl ' s     [1]
38. 469.64 bbl ' s water     [1]
39. 8 " sow     [1]
40. w / 4 k     [1]
41. 2 s at shakers . repaired     [1]
42. 2 s . rotate drilled 8265     [1]
43. trace h 2 s at shakers     [1]
44. 2 s at     [1]
45. pipe 90 ’ w     [1]
46. h 2 s . ran 15 joints     [1]
47. h 2 s . rotate drilled     [1]
48. w / 11034 psi . no     [1]
49. h 2 s . held safety     [1]

Please enter the indices, separated by spaces, of all of the patterns you wish to select.
Or enter s to skip this entity or v to search by value.

Processing the entity: pump rate max (bpm)
This entity hasn't been learned yet.
Looking for patterns that are similar to the entity name.
Found similar patterns

I found the following patterns that may represent pump rate max (bpm).

0. max rate 81.6 bpm .     [3]
1. 1000 gals acid . max rate 12     [1]
2. ops standby stg # 29 max rate     [1]
3. max rate 12     [7]
4. ops stg # 13 max rate avg     [11]
5. frac ops stg # 13 max rate     [11]
6. 9,264 8,815 max rate     [4]
7. gals acid . max rate 12 bpm     [1]
8. max psi 7550 # max rate 15     [1]
9. max rate 81.6 bpm . isip 5499     [3]
10. psi 9020 . max rate 76.7     [1]
11. 9020 . max rate 76.7     [1]
12. repair eline stg # 23 max rate     [1]
13. eline stg # 23 max rate     [1]
14. pumps . stg # 21 max rate     [1]
15. max rate 12 bpm @ 9600     [1]
16. max psi 9020 . max rate 76.7     [1]
17. 26 . stg # 24 max rate     [1]
18. max rate 12 bpm     [7]
19. max psi 9020 . max rate     [1]
20. resumed stg # 18 max rate     [1]
21. 9020 . max rate     [1]
22. 3/8 pac pin x 1.5 " mt     [1]
23. mbr : 10.4     [1]
24. acid . max rate 12 bpm @     [1]
25. stg # 13 max rate     [17]
26. 9020 . max rate 76.7 bpm     [1]
27. 1000 gals acid . max rate     [1]
28. psi 9020 . max rate     [1]
29. mbr : 10.4 °     [1]
30. 7550 # max rate 15 bpm .     [1]
31. standby stg # 29 max rate     [1]
32. 14,742 ' 9,264 8,815 max rate     [4]
33. psi 7550 # max rate     [1]
34. acid . max rate 12 bpm     [1]
35. 7550 # max rate 15 bpm     [1]
36. psi 7550 # max rate 15     [1]
37. max rate 12 bpm @ 9600 #     [1]
38. 8,815 max rate     [21]
39. max psi 7550 # max rate     [1]
40. mbr : 10.4 ° ♦ note :     [1]
41. valves . stg # 19 max rate     [1]
42. 7550 # max rate 15     [1]
43. acid . max rate 12     [1]
44. 7550 # max rate     [1]
45. 9.3 ° - mbr     [1]
46. max rate 81.6 bpm . isip     [3]
47. ops stg # 13 max rate     [11]
48. gals acid . max rate 12     [1]
49. max rate 12 bpm @     [1]

Please enter the indices, separated by spaces, of all of the patterns you wish to select.
Or enter s to skip this entity or v to search by value.
o 1 2
Traceback (most recent call last):
  File "knowledge_facilitator.py", line 65, in <module>
    cli()
  File "C:\Users\ugwz\AppData\Local\Continuum\anaconda3\envs\jpl\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ugwz\AppData\Local\Continuum\anaconda3\envs\jpl\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\ugwz\AppData\Local\Continuum\anaconda3\envs\jpl\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ugwz\AppData\Local\Continuum\anaconda3\envs\jpl\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "knowledge_facilitator.py", line 61, in cli
    interface.single_doc_cli(path, strict, a)
  File "C:\Users\ugwz\T-ENTacle\text-analysis\KE_interface.py", line 225, in single_doc_cli
    self.interact_for_single_entity(entity_name, strict=strict, auto_skip=auto_skip)
  File "C:\Users\ugwz\T-ENTacle\text-analysis\KE_interface.py", line 174, in interact_for_single_entity
    selection = self.get_user_selection(entity_name, close_patterns+far_patterns, True)
  File "C:\Users\ugwz\T-ENTacle\text-analysis\KE_interface.py", line 91, in get_user_selection
    patterns_to_keep = [patterns[int(i)] for i in pattern_selection if i]
  File "C:\Users\ugwz\T-ENTacle\text-analysis\KE_interface.py", line 91, in <listcomp>
    patterns_to_keep = [patterns[int(i)] for i in pattern_selection if i]
ValueError: invalid literal for int() with base 10: 'o'
```

**Comment by cosmoshsv** [comment]
Hi @shuxingcheng , there's an issue in the inputs provided - 'o' character has been used instead of 0(zero)
> Please enter the indices, separated by spaces, of all of the patterns you wish to select.
> Or enter s to skip this entity or v to search by value.
> o 1 2

Assuming it to be a negative test case, we'll analyse and provide a user-friendly error message.
